Vagrant.configure("2") do |config|
  #Lisätään /src jaettuihin kansioihin
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../src", "/vagrant/src", type: "rsync", :mount_options => ["dmode=777", "fmode=666"], rsync__exclude: ['node_modules/', 'map-app/node_modules/']
  #Käteetään yksinkertaista virtuaalilaatikkoa
	config.vm.box = "ubuntu/bionic64"
  #Luetaan tarvittavat lisät seuraavasta tiedostosta
	config.vm.provision :shell, path: "bootstrap.sh"
  #Serverin portti
	config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3306, host: 3306#Mysql
  
end