INSERT INTO Segmentit (Nimi,Maasto,Lumivyöryvaara,On_Alasegmentti)
VALUES('Metsä', 'Metsä', FALSE, null),
      ('Laukukero Pohjoisseinä', 'Tuulikangas', FALSE, null),
      ('Lehmäkero länsiseinä ja laakso', 'Tuulikangas ja varvikko', FALSE, null),
      ('Orotuskero eteläseinä ja laakso', 'Tuulikangas ja varvikko', FALSE, null),
      ('Paratiisikuru', 'Tuulikangas, keskellä rehevä katajainen joenuoma', FALSE, null),
      ('Pallas-Palkas itäseinä', 'Rakka, puurajassa varvikko', FALSE, null),
      ('Laukukero itäseinä', 'Tuulikangas ja varvikko', FALSE, null),
      ('Laukukero länsiseinä', 'Tuulikangas ja varvikko', FALSE, null),
      ('Pallas-Palkas länsiseinä', 'Tuulikangas ja varvikko', FALSE, null),
      ('Vatikuru', 'Tuulikangas alaosassa puronvarsilla katajikko', FALSE, null),
      ('Pyhä-Lehmäkero itäseinä', 'Raakakivikko', FALSE, null),
      ('Pyhäkero eteläseinä', 'Raakakivikko ja tuulikangas', FALSE, null),
      ('Paratiisikuru', 'Vakio', FALSE, 5),
      ('Pyhäkuru', 'Vakio', TRUE, 11),
      ('Soilenrinne', 'Vakio', FALSE, 8),
      ('Veitikka', 'Vakio', FALSE, 10),
      ('Viivakuru', 'Vakio', FALSE, 6),      
      ('Orotuskero pohjoinen', 'Kivirakka, alhaalla kosteikkoa', FALSE, null);
